name: Wall bot tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Wall bot tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest-cov
          pip install -r requirements.txt

      - name: Test
        env:
          PYTHONPATH: .
        run: |
          python3 -m pytest --cov --cov-report=xml -v tests

      - name: Lint with flake8
        run: |
          flake8 *.py tests --count --show-source --statistics

      - name: Coverage upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          name: wall-bot
